# Generated by Django 6.0.6 on 2026-06-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyprofile',
            name='password',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='password',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
